name: Automatic Rebase

on:
  issue_comment:
    types: [ created ]

jobs:
  rebase:
    name: Rebase
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/rebase')
    runs-on: ubuntu-latest
    permissions:
      workflow: write
      issues: write
      actions: write
      contents: write
      checks: write
      deployments: write
      packages: write
      pull-requests: write
      repository-projects: write
      statuses: write
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      - name: Automatic Rebase
        uses: cirrus-actions/rebase@1.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  call-pipeline:
    uses: angelobretenovv/test-rebase/.github/workflows/actions.yml@main
