name: Automatic Rebase

on:
  issue_comment:
    types: [ created ]

jobs:
  rebase:
    name: Rebase
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/rebase')
    runs-on: ubuntu-latest
    steps:
      - name: Get Personal Access Token Based on User
        env:
          ACTOR: ${{ github.actor }}_pat
        run: |
          echo "ACTOR=$(echo ${ACTOR})" >> $GITHUB_ENV
      - name: Checkout the latest code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.${{env.ACTOR}} }}
          fetch-depth: 0
      - name: Automatic Rebase
        uses: cirrus-actions/rebase@1.5
        env:
          GITHUB_TOKEN: ${{ secrets.${{env.ACTOR}} }}
  call-pipeline:
    uses: angelobretenovv/test-rebase/.github/workflows/actions.yml@main
