name: Automatic Rebase

on:
  issue_comment:
    types: [ created ]

jobs:
  rebase:
    name: Rebase
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/rebase')
    runs-on: ubuntu-latest
    steps:
      - name: Echo GH context
        env:
          ACTOR: ${{ toJSON(github.actor) }}
        run: echo "$ACTOR" && echo "$secrets.$($ACTOR)_pat"
      - name: Get Personal Access Token Based on User
        run: |
          echo "PAT_TOKEN=$(echo $secrets.$(github.actor)_pat | cut -c 1-6)" >> $GITHUB_ENV
      - name: Checkout the latest code
        uses: actions/checkout@v2
        with:
          token: ${{ env.PAT_TOKEN }}
          fetch-depth: 0
      - name: Automatic Rebase
        uses: cirrus-actions/rebase@1.5
        env:
          GITHUB_TOKEN: ${{ env.PAT_TOKEN }}
  call-pipeline:
    uses: angelobretenovv/test-rebase/.github/workflows/actions.yml@main
